name: Run E2E Tests

on: [pull_request]

jobs:
  run-e2e-tests:
    name: Run E2E Tests
    runs-on: ubuntu-latest

    services: # adicionando o container do docker compose
      api-solid-pg:
        image: bitnami/postgresql
        ports:
          - 5432:5432
        environment:
          - POSTGRESQL_USERNAME=docker
          - POSTGRESQL_PASSWORD=docker
          - POSTGRESQL_DATABASE=ignitenode03


    steps: # passo a passo para rodar o projeto
      - uses: actions/checkout@v3 # baixa o codigo na maquina
      - uses: actions/setup-node@v3 # instalar o node
        with:
          node-version: 18 #versão do node
          cache: 'yarn' # criar um cache para reaproveitar as dependencias
      - run: yarn install --frozen-lockfile # instalar o projeto
      - run: yarn run test:e2e # executar os testes end to end
        env: # passando as variaveis de ambiente
          JWT_SECRET: testing
          DATABASE_URL: "postgresql://docker:docker@localhost:5432/apisolid?schema=public"